"""empty message

Revision ID: f1e943279375
Revises: d2d75bae3803
Create Date: 2020-11-24 14:12:36.561254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e943279375'
down_revision = 'd2d75bae3803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue', sa.Integer(), nullable=True))
    op.drop_constraint('Show_show_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue'], ['id'])
    op.drop_column('Show', 'show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_show_fkey', 'Show', 'Venue', ['show'], ['id'])
    op.drop_column('Show', 'venue')
    # ### end Alembic commands ###
